/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface ActionLink {
    'linkText': string;
  }
  interface AppHome {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface ShippingForm {
    'linkText': string;
  }
  interface ShippingRates {
    'name': string;
    'rate': string;
    'zone': string;
  }
}

declare global {


  interface HTMLActionLinkElement extends Components.ActionLink, HTMLStencilElement {}
  var HTMLActionLinkElement: {
    prototype: HTMLActionLinkElement;
    new (): HTMLActionLinkElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLShippingFormElement extends Components.ShippingForm, HTMLStencilElement {}
  var HTMLShippingFormElement: {
    prototype: HTMLShippingFormElement;
    new (): HTMLShippingFormElement;
  };

  interface HTMLShippingRatesElement extends Components.ShippingRates, HTMLStencilElement {}
  var HTMLShippingRatesElement: {
    prototype: HTMLShippingRatesElement;
    new (): HTMLShippingRatesElement;
  };
  interface HTMLElementTagNameMap {
    'action-link': HTMLActionLinkElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'shipping-form': HTMLShippingFormElement;
    'shipping-rates': HTMLShippingRatesElement;
  }
}

declare namespace LocalJSX {
  interface ActionLink {
    'linkText'?: string;
  }
  interface AppHome {}
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface AppRoot {}
  interface ShippingForm {
    'linkText'?: string;
  }
  interface ShippingRates {
    'name'?: string;
    'rate'?: string;
    'zone'?: string;
  }

  interface IntrinsicElements {
    'action-link': ActionLink;
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'shipping-form': ShippingForm;
    'shipping-rates': ShippingRates;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'action-link': LocalJSX.ActionLink & JSXBase.HTMLAttributes<HTMLActionLinkElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'shipping-form': LocalJSX.ShippingForm & JSXBase.HTMLAttributes<HTMLShippingFormElement>;
      'shipping-rates': LocalJSX.ShippingRates & JSXBase.HTMLAttributes<HTMLShippingRatesElement>;
    }
  }
}


